[workspace]
resolver = "2"

members = [
    "bus_behavior",
    "hello_pico_ram",
    "hello_pico",
    "hello_pico_multicore",
    "pico_rtic_timer",
    "pico_rtic_timer_ram",
    "pico_simple_timer",
    "cross_core_demos",
]
